'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SuspeitoServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Suspeito", [Namespace]:="http://schemas.datacontract.org/2004/07/InterValor.WCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Suspeito
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdSuspeitoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdSuspeito() As Integer
            Get
                Return Me.IdSuspeitoField
            End Get
            Set
                If (Me.IdSuspeitoField.Equals(value) <> true) Then
                    Me.IdSuspeitoField = value
                    Me.RaisePropertyChanged("IdSuspeito")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomeField, value) <> true) Then
                    Me.NomeField = value
                    Me.RaisePropertyChanged("Nome")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SuspeitoServiceReference.ISuspeitoService")>  _
    Public Interface ISuspeitoService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISuspeitoService/ListarTodos", ReplyAction:="http://tempuri.org/ISuspeitoService/ListarTodosResponse")>  _
        Function ListarTodos() As SuspeitoServiceReference.Suspeito()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISuspeitoService/ListarTodos", ReplyAction:="http://tempuri.org/ISuspeitoService/ListarTodosResponse")>  _
        Function ListarTodosAsync() As System.Threading.Tasks.Task(Of SuspeitoServiceReference.Suspeito())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISuspeitoServiceChannel
        Inherits SuspeitoServiceReference.ISuspeitoService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SuspeitoServiceClient
        Inherits System.ServiceModel.ClientBase(Of SuspeitoServiceReference.ISuspeitoService)
        Implements SuspeitoServiceReference.ISuspeitoService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListarTodos() As SuspeitoServiceReference.Suspeito() Implements SuspeitoServiceReference.ISuspeitoService.ListarTodos
            Return MyBase.Channel.ListarTodos
        End Function
        
        Public Function ListarTodosAsync() As System.Threading.Tasks.Task(Of SuspeitoServiceReference.Suspeito()) Implements SuspeitoServiceReference.ISuspeitoService.ListarTodosAsync
            Return MyBase.Channel.ListarTodosAsync
        End Function
    End Class
End Namespace
